
if(!require(plyr) install.packages("plyr")
if(!require(ggplot2) install.packages("ggplot2")
if(!require(lme4) install.packages("lme4")
if(!require(reshape2) install.packages("reshape2")
#if(!require(animation)) install.packages("animation")
if(!require(languageR) install.packages("languageR")
if(!require(matrixcalc) install.packages("matrixcalc")
if(!require(lattice) install.packages("lattice")
if(!require(multcomp) install.packages("multcomp")
if(!require(gmodels) install.packages("gmodels")

source("ggbiplot.R")
setwd("~/Documents/R/Exp1Rev")
source("filterdataNA.R")
source("summarySE.R")
source("buildfingmatp.R")
source("buildsubmatap.R")
source("tqallsubmat.R")
source("tqyztrial.R")
source("anio.R")
source("calcAnioCoef.R")
source("lrntrial.R")
source("dslrntrial.R")
source("buildsubmatap2fing.R")
source("buildsubmatap3fing.R")
source("buildsubmatap4fing.R")
source("buildsubmatoff.R")
source("buildfingmatoff.R")
source("dataReogPlot.R")
setwd("./synKinDyn_Rcode")
source("sortData.R")
source("aveMat.R")
setwd("./synKinDyn_Rcode/data")
